import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'

import { FormEvent, useContext, useState } from 'react'

// Components
import { ButtonForm, InputForm } from '@/components/Form/ElementsForm'

import { toast } from 'react-toastify'

// Context
import { AuthContext } from '@/contexts/AuthContext'
import { canSSRguest } from '@/utils/canSSRguest'

export default function Home() {

  const { authLogin,loadingAuth } = useContext(AuthContext);

  const [email, setEmail] = useState<string>('');
  const [password, setPassword] = useState<string>('');

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    if(email === '' || password === ''){
      toast.warning("Preencha todos os campos!")
      return;
    }

    let data = {
      email,
      password
    }

    authLogin(data)
  }

  return (
    <>
      <Head>
        <title>Faça seu login - React Gram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <article className={styles.container}>
        <form onSubmit={handleSubmit} className={styles.form}>
          <h1>Faça seu login</h1>
          <p className={styles.subtitle}>Faça o login para ver o que há de novo</p>
          <label>
            <span>Email:</span>
            <InputForm 
              type='text'
              placeholder='Digite seu email'
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </label>
          <label>
            <span>Senha:</span>
            <InputForm 
              type='password'
              placeholder='Digite sua senha'
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </label>
          <ButtonForm loading={loadingAuth} >
            Entrar
          </ButtonForm>
          
          <Link href="/register" className={styles.linkForm}>Ainda não tem conta? Clique aqui!</Link>
        </form>
      </article>
    </>
  )
}


export const getServerSideProps = canSSRguest(async (ctx) => {

  return {
    props: {}
  }

})