import React, { FormEvent, useContext, useState } from 'react';
import Link from 'next/link';
import Head from 'next/head';

import styles from '@/styles/Home.module.css'

import {toast} from 'react-toastify';

// Components
import { ButtonForm, InputForm } from '@/components/Form/ElementsForm';

// Context
import { AuthContext } from '@/contexts/AuthContext';
import { canSSRguest } from '@/utils/canSSRguest';


export default function Register(){

    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [confirmPassword, setConfirmPassword] = useState('');

    const { authRegiste, loadingAuth } = useContext(AuthContext);

    const handleSubmit = (e: FormEvent) => {
        e.preventDefault();

        if(!name || !email || !password || !confirmPassword){
            toast.warning("Preencha todos os campos")
            return;
        }

        const data = {
            name,
            email,
            password,
            confirmPassword
        }

        authRegiste(data);
    }

  return (
    <>
      <Head>
        <title>Faça seu cadastro - React Gram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <article className={styles.container}>
          <form onSubmit={handleSubmit} className={styles.form}>
            <h2>ReactGram</h2>
            <p className={styles.subtitle}>Cadastre-se agora!</p>
            <label>
              <span>Nome:</span>
              <InputForm 
                type='text'
                placeholder='Digite seu nome'
                value={name}
                onChange={e => setName(e.target.value)}
              />
            </label>
            <label>
              <span>Email:</span>
              <InputForm 
                type='email'
                placeholder='Digite seu email'
                value={email}
                onChange={e => setEmail(e.target.value)}
              />
            </label>
            <label>
              <span>Senha:</span>
              <InputForm 
                type='password'
                placeholder='Digite sua senha'
                value={password}
                onChange={e => setPassword(e.target.value)}
              />
            </label>
            <label>
              <span>Confirme sua senha:</span>
              <InputForm 
                type='password'
                placeholder='Confirme sua senha'
                value={confirmPassword}
                onChange={e => setConfirmPassword(e.target.value)}
              />
            </label>
            <ButtonForm loading={loadingAuth} type='submit' >
              Cadastrar
            </ButtonForm>
            <Link href="/" className={styles.linkForm}>Já possui uma conta? Clique aqui!</Link>
          </form>
        </article>
    </>
  )
}

export const getServerSideProps = canSSRguest(async (ctx) => {

    return {
        props: {}
    }

})